### ISSUE TITLE
Object is not a committish 

### ISSUE THREAD

**Issue by StanleyShen** [cloudfoundry-community/cf-boshworkspace#91]
When I was trying on this repo for CF deployment,  I follow the steps and met some questions/concerns:

1) Define properties

```
export CF_DOMAIN=<domain, like prod.mycloudfoundry.domain or 1.2.3.4.xip.io>
Q: should this domain exist or not? If I already have a domain like 'stanley.io.', will the deployment impact on it?

export IPMASK=<First two octects of IP range to use, set in 10.x, like 10.10>
export CF_SUBNET1=<ID of first subnet to use for CF machines, like sg-deadbeef>
export CF_SUBNET2=<ID of second subnet to use for CF machines, like sg-deadbeef>
export LB_SUBNET1=<ID of subnet to use for loadbalancer, like sg-deadbeef>
Q: we should pre-define these subnets, right? 

export CF_SG=<Name of the security group to use for Cloud Foundry machines, like cf or cf-security-group>
Q: should we pre-define it and what ports need to be opened?
```

2) bosh prepare deployment
The network is quite slow, so I upload the release manually via "bosh upload release https://community-shared-boshreleases.s3.amazonaws.com/boshrelease-cf-196.tgz"
After that, I continuously met below problems, even after I deleted the release

```
Fetching release 'cf' to satisfy template references
Object is not a committish.
```

What should I do for it?

3) any support for diego
I see some files/properties defined for diego, and I didn't see deployment description for diego?

Thanks in advance if some questions are obviously clear to you.
Just to make it clear for newbie.

**Comment by MRosker** [comment]
It worked for me, to delete .stemcells and .releases folder from the cf-boshworkspace and run

```
bosh prepare deployment
```

once more.
